apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
  - plugin:
      configMapRef:
        name: argocd-fleet-sync
      input:
        parameters:
          fleetProjectNumber: "$FLEET_PROJECT_NUMBER"
      requeueAfterSeconds: 10
  template:
    metadata:
      name: '{{ nameShort }}-ingress-nginx'
    spec:
      project: default
      source:
        path: ''
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.10.5
        chart: ingress-nginx
      destination:
        server: '{{ server }}'
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/template/spec/containers/0/resources/requests/memory