apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: application-gateway
  namespace: istio-system
spec:
  selector:
    app: application-gateway-controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.coldbrewlabs.ca"
