apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/jukebox

patches:
- target:
    kind: VirtualService
    name: jukebox
  patch: |-
    - op: replace
      path: /spec/hosts/0
      value: jukebox.np-nane2.cloud.coldbrewlabs.ca